ports:
- port: 3000
tasks:
- init: cd utils
- init: npm install
- init: pip3 install awscli --upgrade --user
- init: npm install express --save
- init: npm install aws-serverless-express
- init: npm install serverless -g
# -init: npm install connector-module-name
# Note: package.json also needs to be updaed